language: 
  - shell
osx_image: xcode11
dist: xenial
python:
  - '3.6'
  - '3.7'
  - '3.8'
os:
  - linux
  - osx
  - windows
git:
  depth: 25
  quiet: true
cache: pip
addons:
  apt:
    packages:
      - libpng16-16
      - xfonts-75dpi
      - xfonts-base
      - libffi-dev
      - libxml2-dev
      - libxslt1-dev
      - libssl-dev # for libcrypto.so
before_install:
    - export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
    - export WKHTML_URL=https://downloads.wkhtmltopdf.org/0.12/0.12.5/
    - export WKHTML_DEB=wkhtmltox_0.12.5-1.xenial_amd64.deb
    - export WKHTML_PKG=wkhtmltox-0.12.5-1.macos-cocoa.pkg
    - export JAVA_HOME="/c/Program Files/OpenJDK/jdk-13.0.2"
    - export PATH=/c/Python37:/c/Python37/Scripts:$JAVA_HOME/bin:$PATH
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget ${WKHTML_URL}${WKHTML_DEB} && sudo dpkg -i ${WKHTML_DEB}; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget ${WKHTML_URL}${WKHTML_PKG} && sudo installer -pkg ${WKHTML_DEB} -target /; fi
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install python --version 3.7.5 && choco install wkhtmltopdf --version 0.12.5 && choco install openjdk --version 13.0.102; fi
install:
- set PYTHONIOENCODING=UTF8
- pip3 install --upgrade pip || python -m pip install --upgrade pip
before_script:
- pip3 install --upgrade tox
- pip3 install --no-index --find-links=scripts/wheels yara-python
- pip3 install --no-cache-dir -r requirements.txt
- python3 manage.py makemigrations || python manage.py makemigrations
- python3 manage.py migrate || python manage.py migrate
- git submodule update --init --recursive
script:
- tox -e lint
- python3 manage.py test || python manage.py test
notifications:
  slack: mobsf:4Ce13XOnMRzFG3bqQ0Hap7OP
  
